### ISSUE TITLE
QA_Building POS Tagger_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#10]
Defect Description :
In the "Building POS Tagger" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user                       

Actual Result :
In the "Building POS Tagger" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Building%20POS%20Tagger/Building%20POS%20Tagger_11_Back%20to%20experiments_smk.org

Attachment:
![nlp31](https://cloud.githubusercontent.com/assets/14869397/14775178/bcd7eb44-0ada-11e6-911d-55ebed22f163.png)

**Comment by sravanthimodepu** [comment]
This issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #10
