### ISSUE TITLE
QA_Building POS Tagger_Further Readings_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#11]
Defect Description :
When we click on further readings page of"Building POS Tagger"the alignment of the text are not in order instead the test should be clear in order to maintain the page utility                     

Actual Result :
When we click on further readings page of"Building POS Tagger"the alignment of the text are not in order

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Building%20POS%20Tagger/Building%20POS%20Tagger_09_Further%20Readings_smk.org

Attachment:
![nlp30](https://cloud.githubusercontent.com/assets/14869397/14775160/9356da50-0ada-11e6-9395-2c095877fffc.png)

**Comment by BSravanthi** [comment]
Closed #11
