### ISSUE TITLE
QA_Building POS Tagger_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#12]
Defect Description :
In simulator page of"Building POS Tagger" experiment,when we refresh the page, the page it is redirecting to introduction ,where the simulator page should be reloaded.                     

Actual Result :
In simulator page of"Building POS Tagger" experiment,when we refresh the page, the page it is redirecting to introduction

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Building%20POS%20Tagger/Building%20POS%20Tagger_05_Experiment_smk.org

Attachment:
![nlp29](https://cloud.githubusercontent.com/assets/14869397/14775148/82a435a4-0ada-11e6-9c65-9c28f5485f04.png)

**Comment by sravanthimodepu** [comment]
Issue is resolved.

**Comment by BSravanthi** [comment]
Closed #12
