### ISSUE TITLE
QA_POS Tagging: Viterbi Decoding_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#13]
Defect Description :
In the "POS Tagging: Viterbi Decoding" experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required                    

Actual Result :
In the "POS Tagging: Viterbi Decoding" experiment, the minimum requirement to run the experiment is not displayed in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/POS%20Tagging%20Viterbi%20Decoding/POS%20Tagging%20Viterbi%20Decoding_14_Prerequisites_p1.org

Attachment:
![nlp28](https://cloud.githubusercontent.com/assets/14869397/14775136/648f5a08-0ada-11e6-8a1f-4e372954faec.png)

**Comment by sravanthimodepu** [comment]
This issue is differed.

**Comment by BSravanthi** [comment]
The lab does not require any client side dependencies. Any user having a machine with Internet browser can run these experiment. Hence closing the issue.
