### ISSUE TITLE
QA_POS Tagging: Viterbi Decoding_Further Readings_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#15]
Defect Description :
When we click on further readings page of"POS Tagging: Viterbi Decoding"the alignment of the text are not in order instead the test should be clear in order to maintain the page utility                  

Actual Result :
When we click on further readings page of"POS Tagging: Viterbi Decoding"the alignment of the text are not in order
Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/POS%20Tagging%20Viterbi%20Decoding/POS%20Tagging%20Viterbi%20Decoding_11_Further%20Readings_smk.org

Attachment:
![nlp26](https://cloud.githubusercontent.com/assets/14869397/14775123/40668e3a-0ada-11e6-939a-43a77fc0c8bb.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #15
