### ISSUE TITLE
QA_POS Tagging: Viterbi Decoding_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#16]
Defect Description :
In simulator page of"POS Tagging: Viterbi Decoding" experiment,when we refresh the page, the page it is redirecting to introduction ,where the simulator page should be reloaded.                  

Actual Result :
In simulator page of"POS Tagging: Viterbi Decoding" experiment,when we refresh the page, the page it is redirecting to introduction

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/POS%20Tagging%20Viterbi%20Decoding/POS%20Tagging%20Viterbi%20Decoding_05_Experiment_smk.org

Attachment:
![nlp25](https://cloud.githubusercontent.com/assets/14869397/14775091/00cbd546-0ada-11e6-9e8f-29c7b30c7d3b.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #16
