### ISSUE TITLE
QA_POS Tagging: Hidden Markov Model_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#18]
Defect Description :
In the "POS Tagging: Hidden Markov Model" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user                 

Actual Result :
In the "POS Tagging: Hidden Markov Model" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/POS%20Tagging%20Hidden%20Markov%20Model/POS%20Tagging%20Hidden%20Markov%20Model_13_Back%20to%20experiments_smk.org

Attachment:
![nlp23](https://cloud.githubusercontent.com/assets/14869397/14775027/82fb7d24-0ad9-11e6-9f76-9074b9df5fcb.png)

**Comment by sravanthimodepu** [comment]
This issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #18
