### ISSUE TITLE
QA_Building Chunke_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#2]
Defect Description :
In the "Building Chunker" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user                             

Actual Result :
In the "Building Chunker" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Building%20Chunker/Building%20Chunker_11_Back%20to%20experiments_smk.org

Attachment:
![nlp39](https://cloud.githubusercontent.com/assets/14869397/14775276/6990272a-0adb-11e6-8427-4ef9b8005a83.png)

**Comment by khushpreet-kaur** [comment]
In the current UI design, all the `back` navigation happens through browsers back button. All the labs navigation is consistence with this UI.

**Comment by sravanthimodepu** [comment]
This issue is differed.

**Comment by BSravanthi** [comment]
Closed #2
