### ISSUE TITLE
QA_N-Grams Smoothing_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#24]
Defect Description :
In simulator page of"N-Grams Smoothing" experiment,when we refresh the page, the page it is redirecting to introduction ,where the simulator page should be reloaded.             

Actual Result :
In simulator page of"N-Grams Smoothing" experiment,when we refresh the page, the page it is redirecting to introduction

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/N-Grams%20Smoothing/N-Grams%20Smoothing_05_Experiment_smk.org

Attachment:
![nlp17](https://cloud.githubusercontent.com/assets/14869397/14774888/85d12cf2-0ad8-11e6-9322-f4ac781ed0ef.png)

**Comment by sravanthimodepu** [comment]
This issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #24
