### ISSUE TITLE
QA_N-Grams_Further Readings_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#27]
Defect Description :
When we click on further readings page of"N-Grams"the alignment of the text are not in order instead the test should be clear in order to maintain the page utility          

Actual Result :
When we click on further readings page of"N-Grams"the alignment of the text are not in order

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/N-Grams/N-Grams_10_Further%20Readings_smk.org

Attachment:
![nlp14](https://cloud.githubusercontent.com/assets/14869397/14774835/ff037004-0ad7-11e6-8908-7893e338867c.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #27
