### ISSUE TITLE
QA_N-Grams_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#28]
Defect Description :
In simulator page of"N-Grams" experiment,when we refresh the page, the page it is redirecting to introduction ,where the simulator page should be reloaded.          

Actual Result :
In simulator page of"N-Grams" experiment,when we refresh the page, the page it is redirecting to introduction

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/N-Grams/N-Grams_05_Experiment_smk.org

Attachment:
![nlp13](https://cloud.githubusercontent.com/assets/14869397/14774811/a1ebf49a-0ad7-11e6-96c4-a1342ea979dc.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #28
