### ISSUE TITLE
QA_Building Chunke_Further Readings_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#3]
Defect Description :
When we click on further readings page of"Building Chunker"the alignment of the text are not in order instead the test should be clear in order to maintain the page utility                           

Actual Result :
When we click on further Reading page of"Building Chunker"the alignment of the text are not in order

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Building%20Chunker/Building%20Chunker_09_Further%20Readings_smk.org

Attachment:
![nlp38](https://cloud.githubusercontent.com/assets/14869397/14775267/5c31a7d4-0adb-11e6-8527-e08427f6f71c.png)

**Comment by sravanthimodepu** [comment]
Issue is resolved.

**Comment by BSravanthi** [comment]
Not yet fixed

**Comment by BSravanthi** [comment]
Closed #3
