### ISSUE TITLE
QA_Morphology_Further Readings_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#31]
Defect Description :
When we click on further readings page of"Morphology"the alignment of the text are not in order instead the test should be clear in order to maintain the page utility       

Actual Result :
When we click on further readings page of"Morphology"the alignment of the text are not in order

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Morphology/Morphology_11_Further%20Readings_smk.org

Attachment:
![nlp10](https://cloud.githubusercontent.com/assets/14869397/14774750/f7c4e7ce-0ad6-11e6-8706-3387d8412fc8.png)

**Comment by sravanthimodepu** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #31
