### ISSUE TITLE
QA_Morphology_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#32]
Defect Description :
In simulator page of"Morphology" experiment,when we refresh the page, the page it is redirecting to introduction ,where the simulator page should be reloaded.       

Actual Result :
In simulator page of"Morphology" experiment,when we refresh the page, the page it is redirecting to introduction

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Morphology/Morphology_05_Experiment_smk.org

Attachment:
![nlp9](https://cloud.githubusercontent.com/assets/14869397/14774722/a9dcb6ea-0ad6-11e6-8275-4ce3eb679e01.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #32
