### ISSUE TITLE
QA_Word Generation_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#34]
Defect Description :
In the "Word Generation" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user      

Actual Result :
In the "Word Generation" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Word%20Generation/Word%20Generation_12_Back%20to%20experiments_smk.org

Attachment:
![nlp7](https://cloud.githubusercontent.com/assets/14869397/14774679/45cd0a38-0ad6-11e6-9b50-ab39efb909b7.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #34
