### ISSUE TITLE
QA_Word Generation_Further Readings_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#35]
Defect Description :
When we click on further readings page of"Word Generation"the alignment of the text are not in order instead the test should be clear in order to maintain the page utility    

Actual Result :
When we click on further readings page of"Word Generation"the alignment of the text are not in order

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Word%20Generation/Word%20Generation_10_Further%20Readings_smk.org

Attachment:
![nlp6](https://cloud.githubusercontent.com/assets/14869397/14774666/3190406c-0ad6-11e6-8b17-84a714664cd2.png)

**Comment by sravanthimodepu** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Not resolved yet

**Comment by BSravanthi** [comment]
Closed #35
