### ISSUE TITLE
QA_Word Generation_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#36]
Defect Description :
In simulator page of"Word Generation" experiment,when we refresh the page, the page it is redirecting to introduction ,where the simulator page should be reloaded.    

Actual Result :
In simulator page of"Word Generation" experiment,when we refresh the page, the page it is redirecting to introduction

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Word%20Generation/Word%20Generation_05_Experiment_smk.org

Attachment:
![nlp5](https://cloud.githubusercontent.com/assets/14869397/14774623/bb85a7f4-0ad5-11e6-93f8-f4c0ad92813f.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #36
