### ISSUE TITLE
QA_Word Analysis_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#38]
Defect Description :
In the "Word Analysis" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user   

Actual Result :
In the "Word Analysis" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Word%20Analysis/Word%20Analysis_12_Back%20to%20experiments_smk.org

Attachment:
![nlp3](https://cloud.githubusercontent.com/assets/14869397/14774439/bd5f3920-0ad3-11e6-829a-2c86c02e3342.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #38
