### ISSUE TITLE
QA_Word Analysis_Further Readings_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#39]
Defect Description :
When we click on further readings page of"Word Analysis"the alignment of the text are not in order instead the test should be clear in order to maintain the page utility 

Actual Result :
When we click on further readings page of"Word Analysis"the alignment of the text are not in order

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Word%20Analysis/Word%20Analysis_10_Further%20Readings_smk.org

Attachment:
![nlp2](https://cloud.githubusercontent.com/assets/14869397/14774393/669d194a-0ad3-11e6-99b3-c8a6d2948819.png)

**Comment by sravanthimodepu** [comment]
This issue is fixed now.

**Comment by BSravanthi** [comment]
Closed #39
