### ISSUE TITLE
QA_Building Chunke_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#4]
Defect Description :
In simulator page of"Building Chunker" experiment,when we refresh the page, the page it is redirecting to introduction ,where the simulator page should be reloaded.                           

Actual Result :
In simulator page of"Building Chunker" experiment,when we refresh the page, the page it is redirecting to introduction

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Building%20Chunker/Building%20Chunker_05_Experiment_smk.org

Attachment:
![nlp37](https://cloud.githubusercontent.com/assets/14869397/14775255/4393254a-0adb-11e6-869b-be0400546d4e.png)

**Comment by sravanthimodepu** [comment]
Issue is resolved.

**Comment by BSravanthi** [comment]
Closed #4
