### ISSUE TITLE
QA_Natural Language Processing Lab_Landing page_Like Button

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/natural-language-processing-iiith#54]
Defect Description:
In the Landing page of "Natural Language Processing Lab", the like button is redirecting to the page which is not found. Where as the page should redirect to the appropriate Vlabs face book page.

Actual Result :
In the Landing page of "Natural Language Processing Lab", the like button is redirecting to the page which is not found.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_nlp_i1](https://cloud.githubusercontent.com/assets/13479177/20002724/18f75156-a2a4-11e6-8663-21278a18bfa6.png)

**Comment by sravanthimodepu** [comment]
Issue is not yet fixed.
