### ISSUE TITLE
QA_Home Page_Unwanted Text

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/natural-language-processing-iiith#56]
Defect Description:
In the Home page of "Natural Language Processing Lab", when we select the entire page, unwanted test is present. Where as the unwanted text should not be present near the Heading.

Actual Result
In the Landing page of "Natural Language Processing Lab", when we click on the View About Page in Studio button a new page is opening with an error message saying Unable to Connect.

Environment:
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_nlp_i3](https://cloud.githubusercontent.com/assets/13479177/20003057/fb091862-a2a5-11e6-8ac8-63d4dfa97fac.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.
