### ISSUE TITLE
QA_Chunking_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/natural-language-processing-iiith#6]
Defect Description :
In the "Chunking" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user                          

Actual Result :
In the "Chunking" experiment,the back to experiments link is not present in the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/natural-language-processing-iiith/blob/master/test-cases/integration_test-cases/Chunking/Chunking_11_Back%20to%20experiments_smk.org

Attachment:
![nlp35](https://cloud.githubusercontent.com/assets/14869397/14775240/28ab3524-0adb-11e6-9129-1f79d6f526f9.png)

**Comment by sravanthimodepu** [comment]
Issue is resolved.

**Comment by BSravanthi** [comment]
Closed #6
